"""2 checkout press account

Revision ID: d0d6955a2dce
Revises: 46fd38798de5
Create Date: 2020-01-27 20:43:15.725255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0d6955a2dce'
down_revision = '46fd38798de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_press_accounts',
    sa.Column('creation_date', sa.Integer(), nullable=False),
    sa.Column('modification_date', sa.Integer(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('modifier', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payer_id', postgresql.UUID(), nullable=False),
    sa.Column('receiver_id', postgresql.UUID(), nullable=False),
    sa.Column('receiver_account_id', postgresql.UUID(), nullable=True),
    sa.Column('payment_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['payer_id'], ['persons.id'], name=op.f('fk_tb_checkout_press_accounts_col_payer_id')),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['accounts.id'], name=op.f('fk_tb_checkout_press_accounts_col_receiver_account_id')),
    sa.ForeignKeyConstraint(['receiver_id'], ['persons.id'], name=op.f('fk_tb_checkout_press_accounts_col_receiver_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_checkout_press_accounts')),
    sa.UniqueConstraint('id', name=op.f('checkout_press_accounts_id_key'))
    )
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkout_press_accounts')
    # ### end Alembic commands ###
