"""name added to devic_keys

Revision ID: 85ad2bfc3c1c
Revises: b0477ed025d9
Create Date: 2019-12-04 13:59:51.689928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ad2bfc3c1c'
down_revision = 'b0477ed025d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_codes', sa.Column('name', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_codes', 'name')
        # ### end Alembic commands ###
