"""device-key table added

Revision ID: b0477ed025d9
Revises: b615827bc4dd
Create Date: 2019-11-25 12:29:00.300146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0477ed025d9'
down_revision = 'b615827bc4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_codes',
    sa.Column('creation_date', sa.Integer(), nullable=False),
    sa.Column('modification_date', sa.Integer(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('modifier', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tb_device_codes_col_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_device_codes')),
    sa.UniqueConstraint('code', name=op.f('device_codes_id_key')),
    sa.UniqueConstraint('id', name=op.f('device_codes_id_key'))
    )
    op.drop_constraint('constraints_id_key', 'constraints', type_='unique')
    op.create_unique_constraint(op.f('constraints_id_key'), 'constraints', ['UniqueCode'])
    op.drop_constraint('groups_id_key', 'groups', type_='unique')
    op.create_unique_constraint(op.f('groups_id_key'), 'groups', ['title'])
    op.drop_constraint('persons_id_key', 'persons', type_='unique')
    op.create_unique_constraint(op.f('persons_id_key'), 'persons', ['email'])
    op.drop_constraint('unique_entity_connector_id_key', 'unique_entity_connector', type_='unique')
    op.create_unique_constraint(op.f('unique_entity_connector_id_key'), 'unique_entity_connector', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_entity_connector_id_key'), 'unique_entity_connector', type_='unique')
    op.create_unique_constraint('unique_entity_connector_id_key', 'unique_entity_connector', ['UniqueCode', 'entity_id'])
    op.drop_constraint(op.f('persons_id_key'), 'persons', type_='unique')
    op.create_unique_constraint('persons_id_key', 'persons', ['id'])
    op.drop_constraint(op.f('groups_id_key'), 'groups', type_='unique')
    op.create_unique_constraint('groups_id_key', 'groups', ['id'])
    op.drop_constraint(op.f('constraints_id_key'), 'constraints', type_='unique')
    op.create_unique_constraint('constraints_id_key', 'constraints', ['id'])
    op.drop_table('device_codes')
    # ### end Alembic commands ###
