"""book_content has celery_task fileds now

Revision ID: b615827bc4dd
Revises: 977610ba7c04
Create Date: 2019-11-16 13:43:18.297970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b615827bc4dd'
down_revision = '977610ba7c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_contents', sa.Column('celery_task_id', sa.String(), nullable=True))
    op.add_column('book_contents', sa.Column('content_generated', sa.Boolean(), nullable=True))
    op.drop_constraint('discussion_members_id_key', 'discussion_members', type_='unique')
    op.create_unique_constraint(op.f('discussion_members_id_key'), 'discussion_members', ['id'])
    op.drop_constraint('persons_id_key', 'persons', type_='unique')
    op.create_unique_constraint(op.f('persons_id_key'), 'persons', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('persons_id_key'), 'persons', type_='unique')
    op.create_unique_constraint('persons_id_key', 'persons', ['email'])
    op.drop_constraint(op.f('discussion_members_id_key'), 'discussion_members', type_='unique')
    op.create_unique_constraint('discussion_members_id_key', 'discussion_members', ['group_id', 'person_id'])
    op.drop_column('book_contents', 'content_generated')
    op.drop_column('book_contents', 'celery_task_id')
    # ### end Alembic commands ###
